{% set name = "clease-gui" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14f4ee14277368a6d84f4b720fc9b71a41a28307d95e78d72d7c50a8675b503a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - clease-gui=clease_gui.cli.main_cli:clease_gui_cli

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ipython
    - jupyterlab
    - ipywidgets
    - clease >=0.10.7
    - pandas
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - click >=8.0.0
    - ase >=3.20
    - nglview

test:
  imports:
    - clease_gui
  requires:
    - pip
  commands:
    - pip check
    - clease-gui --version  # Test the CLI runs
    - clease-gui new  # Test we can copy the jupyter notebook

about:
  home: https://gitlab.com/computationalmaterials/clease-gui/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.md
  summary: CLuster Expansion in Atomic Simulation Environment GUI

  description: |
    CLuster Expansion in Atomic Simulation Environment GUI
  doc_url: https://clease-gui.readthedocs.io/
  dev_url: https://gitlab.com/computationalmaterials/clease-gui/

extra:
  recipe-maintainers:
    - atygesen
